base_url = "https://yangminded.com/"
title = "yangminded"
build_search_index = false
generate_feeds = false
compile_sass = true
minify_html = true
hard_link_static = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "light" # light, dark, auto, toggle

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "x", url = "https://x.com/yangminded", icon = "x-twitter" },
    { name = "github", url = "https://github.com/yinglaiyang", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/yinglaiyang/", icon = "linkedin" },
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com"    # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is