name: Makefile - Deploy Blog on Updates to Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.IONOS_SSH_PRIVATE_KEY }}
        known_hosts: ''

    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.IONOS_SSH_HOST }} >> ~/.ssh/known_hosts

    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.21.0

    - name: Deploy the blog.
      run: make deploy
